kind = "web"
previewPath = "/"
title = "PrimeAnalysisTool"
version = "1.0.0"
id = "artifacts/prime-analysis-tool"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19982

[services.development]
run = "pnpm --filter @workspace/prime-analysis-tool run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/prime-analysis-tool", "run", "build" ]
publicDir = "artifacts/prime-analysis-tool/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19982"
BASE_PATH = "/"
